name: MiniGameAPI
main: minigameapi\MiniGameApi
version: 1.0.0
api: [3.0.0-ALPHA12]
author: MiniGameAPI-PM Team
#it's not a team yet hahah
description: The plugin that helps to managing minigame plugins
website: https://github.com/MiniGameAPI-PM
commands:
 minigameapi:
  description: Main command of MiniGameAPI
  usage: "Usage: /minigameapi"
  permission: minigameapi.command.main
permissions:
 exampleplugin.command.main:
  description: "Allows the user to run the example command"
  default: true
