name: MiniGameAPI
main: minigameapi\MiniGameApi
version: ALPHA
api: [3.0.0-ALPHA12]
author: MiniGameAPI-PM Team
#it's not a team yet hahah
description: The plugin that helps to managing minigame plugins
website: https://github.com/MiniGameAPI-PM
commands:
 minigameapi:
  description: Main command of MiniGameAPI
  usage: "Usage: /minigameapi"
  permission: minigameapi.command
permissions:
 minigameapi.command:
  description: "Main command of MiniGameAPI"
  default: true
