name: MiniGameAPI
main: minigameapi\MiniGameApi
version: 1.0.1
api: [3.0.0]
author: MiniGameAPI-PM Team
#it's not a team yet hahah
description: The plugin that helps to managing minigame plugins
website: https://github.com/MiniGameAPI-PM
load: POSTWORLD
permissions:
 minigameapi:
  description: "control all functions of minigameapi"
  default: op
  children:
    minigameapi.join:
      default: true
    minigameapi.quit:
      default: true
    minigameapi.list:
      default: true
    minigameapi.kill:
      default: op
