name: MiniGameAPI
main: minigameapi\MiniGameApi
version: BETA
api: [3.0.0-ALPHA12]
author: MiniGameAPI-PM Team
#it's not a team yet hahah
description: The plugin that helps to managing minigame plugins
website: https://github.com/MiniGameAPI-PM
permissions:
 minigameapi:
  description: "control all functions of minigameapi"
  default: op
  children:
    minigameapi.join:
      default: true
    minigameapi.quit:
      default: true
    minigameapi.list:
      default: true
    minigameapi.kill:
      default: opyy
