name: SeedCape
main: seedCape\SeedCape
version: 1.0.0
api: [3.0.0]
author: djdisodo
website: https://band.us/@seed24
commands:
  망토:
    description: "갓왕고 망토플긴"
    permission: cape.command
    usage: /망토
permissions:
  cape.command:
    default: true
  cape.custom:
    default: op
  cape.add:
    default: op
